---

- name: Configure each node in the PKI tree
  include_tasks: setup_ca_dictionary_node.yml
  vars:
    ca_parameters: "{{ ca_to_define }}"
    ca_dictionary_variable_name: __pki_tree__ca_dictionary
    ca_openssl_configuration_block_variable_name: __pki_tree__ca_openssl_configuration_block
  loop: "{{ pki_ca_list }}"
  loop_control:
    loop_var: ca_to_define
  when: >-
    not (
      cached_ca_dictionary | default(false) and
      __pki_tree__ca_dictionary is defined and
      __pki_tree__ca_dictionary.keys() | length > 0
    )
